FROM dpi-rdc-app:latest

WORKDIR /var/www

USER root

COPY . .

RUN rm -f bootstrap/cache/*.php \
    && composer dump-autoload --no-dev --optimize --no-scripts \
    && mkdir -p storage/logs bootstrap/cache \
    && chmod -R 777 storage bootstrap/cache \
    && chown -R www-data:www-data /var/www

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["php-fpm"]