"""Référentiel par défaut : paramètres et correspondances repris de la version retenue
(Monkole_Activites_Capacites_01-15_Septembre_2026_Version_retenue.xlsx).

Ces valeurs peuvent être complétées sans toucher au code, dans le fichier
Referentiel_Monkole.xlsx (créé au premier lancement à côté du programme).
"""

PARAMETRES = {
    "visites_par_intervenant_jour": 24,
    "seuil_visites_cabinet": 2,
    "cabinets_physiques_csmkl2": 6,
}

# Lits CHME par unité (ordre d'affichage conservé)
LITS = [
    ("Hospi CHIR", 16),
    ("Hospi GO", 54),
    ("Hospi MI", 19),
    ("Hospi Néonat", 19),
    ("Hospi PED", 13),
    ("Hospi URG", 8),
    ("Hospi SIP", 15),
    ("Hospi REA", 8),
]
HORS_UNITES = "Hors unités / UF absente"

# UF de CSMKL2 rattachées à MAISON ROSE (ancien libellé : activités secondaires)
MAISON_ROSE_UF = [
    "Consultation Prénatale Général",
    "IMAGERIE",
    "Exploration Imagerie",
    "Laboratoire",
    "Sage-Femme",
]

# UF des visites -> spécialité affichée (CHME ambulatoire et MAISON ROSE)
UF_SPECIALITE = {
    "Anesthésie": "Anesthésie",
    "Aptitude physique": "Aptitude physique",
    "Cardiologie": "Cardiologie",
    "Chirurgie Générale": "Chirurgie générale",
    "Chirurgie Pédiatrique": "Chirurgie pédiatrique",
    "Consultation Cardiologie": "Cardiologie",
    "Consultation Chirurgie Générale": "Chirurgie générale",
    "Consultation Chirurgie Pédiatrique": "Chirurgie pédiatrique",
    "Consultation Dentistérie": "Dentisterie",
    "Consultation Dermatologie": "Dermatologie",
    "Consultation Endocrinologie": "Endocrinologie",
    "Consultation Gastro-Entérologie": "Gastro-entérologie",
    "Consultation Gynéco-Obstétrique": "Gynécologie / Obstétrique",
    "Consultation Gynécologie": "Gynécologie / Obstétrique",
    "Consultation Hémato-Pédiatrie": "Hématologie pédiatrique",
    "Consultation Hématologie": "Hématologie adulte",
    "Consultation Kinésithérapie": "Kinésithérapie",
    "Consultation Médecine Interne": "Médecine interne",
    "Consultation Médecine de Famille / Générale": "Médecine générale / famille",
    "Consultation Nephrologie": "Néphrologie",
    "Consultation Neuro-Chirurgie": "Neurochirurgie",
    "Consultation Neuro-Psychiatrie": "Neuropsychiatrie",
    "Consultation Neurologie": "Neurologie",
    "Consultation Nutrition": "Nutrition",
    "Consultation ORL": "ORL",
    "Consultation Oncologie": "Oncologie",
    "Consultation Ophtalmologie": "Ophtalmologie",
    "Consultation Orthopédie": "Orthopédie",
    "Consultation Pneumologie": "Pneumologie",
    "Consultation Pré scolaire": "Pédiatrie",
    "Consultation Prénatale Général": "Gynécologie / Obstétrique",
    "Consultation Psychiatrie": "Neuropsychiatrie",
    "Consultation Pédiatrie": "Pédiatrie",
    "Consultation Pédiatrie Générale": "Pédiatrie",
    "Consultation Rhumatologie": "Rhumatologie",
    "Consultation Urologie": "Urologie",
    "Dentisterie": "Dentisterie",
    "Dermatologie": "Dermatologie",
    "Duplicata certificat": "Documents médicaux",
    "ECG": "Cardiologie",
    "Echographie cardiaque Doppler": "Cardiologie",
    "Endocrinologie": "Endocrinologie",
    "Endoscopie": "Gastro-entérologie",
    "Exploration Cardiologie": "Cardiologie",
    "Exploration Imagerie": "Imagerie médicale",
    "Exploration endoscopie (Bronchoscopie)": "Endoscopie respiratoire",
    "Gastroentérologie": "Gastro-entérologie",
    "Gynécologie": "Gynécologie / Obstétrique",
    "Hématologie Adulte": "Hématologie adulte",
    "Hématologie Pédiatrique": "Hématologie pédiatrique",
    "IMAGERIE": "IMAGERIE",
    "Kinésithérapie": "Kinésithérapie",
    "Laboratoire": "Laboratoire",
    "Maladies Infectieuses": "Maladies infectieuses",
    "Médecine Générale/Famille": "Médecine générale / famille",
    "Médecine Interne": "Médecine interne",
    "Nephrologie": "Néphrologie",
    "Neurochirurgie": "Neurochirurgie",
    "Neuropsychiatrie": "Neuropsychiatrie",
    "Nursing": "Soins infirmiers",
    "Nutrition": "Nutrition",
    "ORL": "ORL",
    "Obstétrique": "Gynécologie / Obstétrique",
    "Oncologie": "Oncologie",
    "Ophtalmologie": "Ophtalmologie",
    "Orthopédie": "Orthopédie",
    "Pansements et Orthopédie": "Soins infirmiers / pansements",
    "Pharmacie": "Pharmacie",
    "Pneumologie": "Pneumologie",
    "Psychiatrie": "Neuropsychiatrie",
    "Pédiatrie": "Pédiatrie",
    "Rhumatologie": "Rhumatologie",
    "Sage-Femme": "Sage-Femme",
    "Suivi Chimiothérapie": "Oncologie",
    "Suivi Dentisterie": "Dentisterie",
    "Suivi Kinésitherapie": "Kinésithérapie",
    "Séances ou soins en Kinésitherapie": "Kinésithérapie",
    "Traumatologie": "Traumatologie",
    "Urologie": "Urologie",
}

# Catégorie d'acte Evolucare -> (spécialité, sous-spécialité) harmonisées comme GPS
EVO_CATEGORIES = {
    "ACTE": ("Catégorie à préciser", "ACTE"),
    "Anesthesie-Anesthesie": ("Anesthésie", "Anesthésie"),
    "Chirurgie-Chirurgie pediatrique": ("Chirurgie", "Chirurgie pédiatrique"),
    "Chirurgie-Consultation": ("Chirurgie", "Consultation"),
    "Chirurgie-Neurochirurgie": ("Chirurgie", "Neurochirurgie"),
    "Chirurgie-Orthopedie-tramatologie": ("Chirurgie", "Orthopédie-tramatologie"),
    "Chirurgie-Urologie": ("Chirurgie", "Urologie"),
    "Chirurgie-Viscerale et generale": ("Chirurgie", "Viscérale et générale"),
    "Dentisterie-Dentisterie": ("Dentisterie", "Dentisterie"),
    "Depense Externe-Depense Externe": ("Dépense Externe", "Dépense Externe"),
    "Dermatologie-DERMATOLOGIE": ("Dermatologie", "DERMATOLOGIE"),
    "Endocrinologie-Endocrinologie": ("Endocrinologie", "Endocrinologie"),
    "Endoscopie-Gastro Enterologie": ("Endoscopie", "Gastro-Entérologie"),
    "Gyneco-Gynecologie": ("Gynéco", "Gynécologie"),
    "Hospitalisation-Hospitalisation": ("Hospitalisation", "Hospitalisation"),
    "Hématologie - Hématologie": ("Hématologie", "Hématologie"),
    "Imagerie Medicale-Echographie": ("Imagerie Médicale", "Echographie"),
    "Imagerie Medicale-Mammographie": ("Imagerie Médicale", "Mammographie"),
    "Imagerie Medicale-Radiographie Speciale": ("Imagerie Médicale", "Radiographie Spéciale"),
    "Imagerie Medicale-Radiographie Standard": ("Imagerie Médicale", "Radiographie Standard"),
    "Imagerie Medicale-Scanner": ("Imagerie Médicale", "Scanner"),
    "Kinesitherapie-Kinesitherapie": ("Kinésithérapie", "Kinésithérapie"),
    "Laboratoire-Anatomo - Cytopathologie": ("Laboratoire", "Anatomo - Cytopathologie"),
    "Laboratoire-Bacteriologie": ("Laboratoire", "Bactériologie"),
    "Laboratoire-Biochimie": ("Laboratoire", "Biochimie"),
    "Laboratoire-Hematologie": ("Laboratoire", "Hématologie"),
    "Laboratoire-Hemostases": ("Laboratoire", "Hémostases"),
    "Laboratoire-Immunologie/Endocrinol": ("Laboratoire", "Immunologie/Endocrinol"),
    "Laboratoire-Microbiologie": ("Laboratoire", "Microbiologie"),
    "Laboratoire-Parasitologie": ("Laboratoire", "Parasitologie"),
    "Laboratoire-Prelevement": ("Laboratoire", "Prelevement"),
    "Laboratoire-Serologie": ("Laboratoire", "Sérologie"),
    "Medecine Generale-Consultations": ("Médecine Générale", "Consultations"),
    "Medecine Interne-Cardiologie": ("Médecine Interne", "Cardiologie"),
    "Medecine Interne-Consultation": ("Médecine Interne", "Consultation"),
    "Medecine Interne-Gastro-Enterologie": ("Médecine Interne", "Gastro-Entérologie"),
    "Medecine Interne-Pneumologie": ("Médecine Interne", "Pneumologie"),
    "Medecine Interne-Rhumatologie": ("Médecine Interne", "Rhumatologie"),
    "Monkole 3-Banque de Sang": ("Monkole 3", "Banque de Sang"),
    "Monkole 3-Laboratoire": ("Monkole 3", "Laboratoire"),
    "Neurologie-Neurologie": ("Neurologie", "Neurologie"),
    "Neuropsy-Neuropsychiatrie": ("Neuropsy", "Neuropsychiatrie"),
    "Nursing-Soins Nursing": ("Nursing", "Soins Nursing"),
    "Nutrition-Nutrition": ("Nutrition", "Nutrition"),
    "ORL-Oto-rhino-laryngologie": ("ORL", "Oto-rhino-laryngologie"),
    "Obstetrique-Obstetrique": ("Obstétrique", "Obstétrique"),
    "Oncologie-Oncologie Clinique": ("Oncologie", "Oncologie Clinique"),
    "Ophtalmologie-Ophtalmologie": ("Ophtalmologie", "Ophtalmologie"),
    "Pediatrie-Pediatrie": ("Pédiatrie", "Pédiatrie"),
    "Reanimation-Reanimation": ("Réanimation", "Réanimation"),
    "Service de Base-Repas": ("Service de Base", "Repas"),
    "Services Generaux-Ambulance": ("Services Généraux", "Ambulance"),
    "Services Generaux-Morgue": ("Services Généraux", "Morgue"),
    "Urgence-Urgence": ("Urgence", "Urgence"),
    "Urologie-Urologie": ("Urologie", "Urologie"),
}

# Catégories Evolucare traitées comme produits (hors actes / prestations)
EVO_PRODUITS = ["Medicament", "MEDICAMENT", "Consommable medical"]

# Alias de noms confirmés (nom nettoyé source -> nom regroupé)
ALIAS_MEDECINS = {
    "KALENDA FARID": "KALENDA NUMBI FARID",
    "NKOSI STONE": "NKOSI MUANA STONE",
}
